### ISSUE TITLE
webgl applied to FILTER.JS

### ISSUE THREAD

**Issue by starzhy** [foo123/FILTER.js#4]
wanna know when the webgl can be applied to FILTER.JS

**Comment by foo123** [comment]
hello, i dont know it is not so trivial task (since the API should be uniform and to some extend transparent as well). The implementation has already started (see /webgl folder), but there are some issues that need consideration. In any case it is one of the TODOs with priority, most probably node.js support will be done first and webgl afterwards. This is my plan for further development of filter.js

**Comment by foo123** [comment]
If you are interested latest Filter.js has WebGL support for most filters.
