### ISSUE TITLE
Memory usage and browser crush

### ISSUE THREAD

**Issue by hezhez** [foo123/FILTER.js#8]
Hi !

I have a list of filters that i'm applying on a video tag with the example you gave me.

The problem is when i'm switching between filters and applying filter after filter (not a combo - every filter as an individual like the video example), at first it's fast but after applying 5 or 6 effects, the video starting to become heavy until the browser is crushing.

Do you have any solution for that ?

**Comment by foo123** [comment]
Hmm, there can be various reasons, from bad application to size of video, to type of browser. 

Do you have any live link?

**Comment by foo123** [comment]
If you want to apply multiple filters (which are selected dynamicaly), you should still use a composite filter, because it is much faster (reducing unnecessary transformations between image data and all that).

If you want the filters to be turned on/off dynamicaly there are two approaches

1. Add all filters in the compo and just turn them on/off as needed (compo will take care not to apply any turned off filters)
2. Dynamicaly add/remove filters from the compo stack, using `.add`, `.remove` methods
